# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 7.x version
  - 7.1.0

sudo: false

before_script:
  - composer install --dev --no-progress

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls
